name: wintep_photo_editor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.1
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  pull_to_refresh: ^2.0.0
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  shimmer: ^3.0.0
  lecle_downloads_path_provider: ^0.0.2+8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
